# Generated by Django 5.0.6 on 2024-07-10 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('photoshoot_date', models.DateField()),
                ('locatiom', models.TextField()),
                ('plant_name_serbian', models.CharField(max_length=100)),
                ('plant_name_latin', models.CharField(max_length=100)),
                ('plant_species_serbian', models.CharField(max_length=100)),
                ('plant_species_latin', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('media_type', models.CharField(max_length=100)),
                ('file_names', models.TextField(default='')),
                ('file_sizes', models.TextField(default='')),
            ],
        ),
    ]
