# Generated by Django 5.0.6 on 2024-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_submittedrecord_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedrecord',
            name='session_id',
            field=models.TextField(default=''),
        ),
    ]
