# Generated by Django 5.0.6 on 2024-07-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_submittedrecord_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedrecord',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
    ]
