# Generated by Django 5.0.6 on 2024-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_alter_submittedrecord_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedrecord',
            old_name='media_type',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='submittedrecord',
            name='locatiom',
        ),
        migrations.AlterField(
            model_name='submittedrecord',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
