# Generated by Django 5.0.6 on 2024-07-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0005_rename_media_type_submittedrecord_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serbian_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
            ],
        ),
    ]
