# Generated by Django 5.0.6 on 2024-07-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0008_submittedrecord_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedrecord',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
